server:
  port: 8010
  name: julong-notification-be
  url: http://localhost:8010
  os: windows
  mode: debug

  
# db:
#   host: localhost
#   port: 5432
#   user: postgres
#   password: postgres
#   dbname: julong-notification
#   sslmode: disable
#   timezone: Asia/Jakarta
db:
  host: prasi.avolut.com
  port: 8741
  user: postgres
  password: gEJIfovgvDAroHhqRiKhYVvrkn2OqXfF3tw8xJmnvw7JhrZgN24pTD9iWMIUIUL6
  dbname: julong-sync-notification
  sslmode: disable
  timezone: Asia/Jakarta


session:
  secret: julong-notification-secret
  expiration: 3600 # in seconds
  name: julong-notification-session

csrf:
  secret: julong-notification-csrf-secret
  expiration: 3600 # in seconds
  name: julong-notification-csrf-token

rabbitmq:
  host: amqp://guest:guest@localhost:5672/
  queue: julong_notification