server:
  port: 8010
  name: julong-notification-be
  url: http://localhost:8010
  os: windows

  
db:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: julong-notification
  sslmode: disable
  timezone: Asia/Jakarta

session:
  secret: julong-notification-secret
  expiration: 3600 # in seconds
  name: julong-notification-session

csrf:
  secret: julong-notification-csrf-secret
  expiration: 3600 # in seconds
  name: julong-notification-csrf-token

rabbitmq:
  host: amqp://guest:guest@localhost:5672/
  queue: julong_notification